# Generated by Django 3.1.4 on 2020-12-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_type', models.CharField(choices=[('SOFT', 'Soft (generic) Skill'), ('HARD', 'Hard (specific) Skill')], default='HARD', max_length=4)),
                ('skill_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Clo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clo_name', models.CharField(max_length=200)),
                ('clo_description', models.TextField()),
                ('skill_development_level', models.CharField(choices=[('UI', 'Unconscious Incompetence'), ('CI', 'Conscious Incompetence'), ('CC', 'Conscious Competence'), ('UC', 'Unconscious Competence')], default='UI', max_length=2)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.skill')),
            ],
        ),
    ]
