# Generated by Django 3.1.4 on 2020-12-12 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200)),
                ('content_description', models.TextField()),
                ('content_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group_configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_configuration_name', models.CharField(max_length=200)),
                ('group_configuration_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ibs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibs_name', models.CharField(max_length=200)),
                ('ibs_description', models.TextField()),
                ('ibs_type', models.CharField(choices=[('A', 'Audio'), ('V', 'Visual')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilo_name', models.CharField(max_length=200)),
                ('ilo_description', models.TextField()),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.clo')),
            ],
        ),
        migrations.CreateModel(
            name='Learning_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_activity_name', models.CharField(max_length=200)),
                ('learning_activity_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teaching_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_method_name', models.CharField(max_length=200)),
                ('teaching_method_description', models.TextField()),
                ('teaching_method_suggested_scenario', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Session_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_plan_content_delivery_method', models.TextField()),
                ('session_plan_intended_content_use', models.TextField()),
                ('session_plan_feedback_detail', models.TextField()),
                ('session_plan_participation_detail', models.TextField()),
                ('clo', models.ManyToManyField(to='planner.Clo')),
                ('content', models.ManyToManyField(to='planner.Content')),
                ('ilo', models.ManyToManyField(to='planner.Ilo')),
                ('learning_activity', models.ManyToManyField(to='planner.Learning_activity')),
                ('teaching_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.teaching_method')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_title', models.CharField(max_length=200)),
                ('recommendation_body', models.TextField()),
                ('group_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.group_configuration')),
                ('ibs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.ibs')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.platform')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.skill')),
                ('teaching_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.teaching_method')),
            ],
        ),
    ]
