# Generated by Django 3.1.4 on 2020-12-12 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_content_group_configuration_ibs_ilo_learning_activity_platform_recommendation_session_plan_teaching_'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_plan',
            name='ibs',
            field=models.ManyToManyField(to='planner.Ibs'),
        ),
        migrations.AddField(
            model_name='session_plan',
            name='platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.platform'),
        ),
    ]
