# Generated by Django 3.1.4 on 2020-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_session_plan_session_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibs',
            name='ibs_com_direction',
            field=models.CharField(choices=[('P', 'Desde los estudiantes que asisten presencialmente'), ('R', 'Desde los estudiantes que se conectan de manera remota')], default='P', max_length=1),
        ),
    ]
