# Generated by Django 3.1.4 on 2020-12-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_ibs_ibs_com_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_plan',
            name='group_configuration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planner.group_configuration'),
        ),
    ]
