# Generated by Django 3.1.5 on 2021-01-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_session_plan_group_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='session_plan',
            name='session_plan_ideal_student_outcome',
            field=models.CharField(default='resultado ideal de las LA', max_length=200),
        ),
    ]
